# Generated by Django 5.1.15 on 2026-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_seed_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
